TMDT-Lab06-1212433/TMDT-Lab06-1212433/Models/DetailsModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TMDT_Lab06_1212433.Models
{
    public class DetailsModels
    {
        public string _mssv { get; set; }
        public string _name { get; set; }
        public string _bday { get; set; }

        public DetailsModels(string mssv, string name, string bday)
        {
            _mssv = mssv;
            _name = name;
            _bday = bday;
        }
    }
}

TMDT-Lab06-1212433/TMDT-Lab06-1212433/Models/LoginModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TMDT_Lab06_1212433.Models
{
    public class LoginModels
    {
        public string Username { get; set; }
        public string Password { get; set; }
    }
}

TMDT-Lab06-1212433/TMDT-Lab06-1212433/Controllers/authController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using TMDT_Lab06_1212433.Models;

namespace TMDT_Lab06_1212433.Controllers
{
    public class authController : Controller
    {
        //
        // GET: /auth/
        public ActionResult login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult login(LoginModels model, string returnUrl)
        {
            // Lets first check if the Model is valid or not
            if (ModelState.IsValid)
            {
                string username = model.Username;
                string password = model.Password;
                bool userValid = false;

                if (username == "1212433" && password == "TMDT2015")
                    userValid = true;

                // User found in the database
                if (userValid)
                {

                    FormsAuthentication.SetAuthCookie(username, false);
                    if (Url.IsLocalUrl(returnUrl) && returnUrl.Length > 1 && returnUrl.StartsWith("/")
                        && !returnUrl.StartsWith("//") && !returnUrl.StartsWith("/\\"))
                    {
                        return Redirect(returnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Index", "users");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Username hoặc Password không đúng.");
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        public ActionResult logout()
        {
            FormsAuthentication.SignOut();

            return RedirectToAction("Index", "users");
        }
    }
}

TMDT-Lab06-1212433/TMDT-Lab06-1212433/Controllers/usersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TMDT_Lab06_1212433.Models;

namespace TMDT_Lab06_1212433.Controllers
{
    public class usersController : Controller
    {
        public string mssv = "";
        public List<DetailsModels> lst = new List<DetailsModels>();
        //
        // GET: /users/
        [Authorize]
        public ActionResult Index()
        {
            LoadSessionObject();
            return View();
        }

        private void CreateDB1212433()
        {
            DetailsModels sv;
            sv = new DetailsModels("1212000", "Nguyễn Văn A", "10/10/1994");
            lst.Add(sv);
            sv = new DetailsModels("1212001", "Nguyễn Thị B", "11/10/1994");
            lst.Add(sv);
            sv = new DetailsModels("1212002", "Lê Văn C", "10/12/1994");
            lst.Add(sv);
        }

        /// <summary>
        /// ActionResult for ordinary session(HttpContext).
        /// </summary>
        /// <param name="sessionValue"></param>
        /// <returns></returns>
        public ActionResult SaveSession(string sessionValue)
        {
            try
            {
                CreateDB1212433();
                for (int i = 0; i < lst.Count; i++ )
                {
                    if (lst[i]._mssv == sessionValue)
                    {
                        System.Web.HttpContext.Current.Session["mssv"] = lst[i]._mssv;
                        System.Web.HttpContext.Current.Session["name"] = lst[i]._name;
                        System.Web.HttpContext.Current.Session["bday"] = lst[i]._bday;
                        mssv = lst[i]._mssv;
                    }
                }

                if (mssv == "")
                    System.Web.HttpContext.Current.Session["error"] = "Không tồn tại mssv này.";

                return RedirectToAction("Index");
            }
            catch (InvalidOperationException)
            {
                return View("Index");
            }
        }

        /// <summary>
        /// Store the session value to ViewData.
        /// </summary>
        private void LoadSessionObject()
        {
            // Load session from HttpContext.
            ViewData["mssv"] = System.Web.HttpContext.Current.Session["mssv"] as String;
            ViewData["name"] = System.Web.HttpContext.Current.Session["name"] as String;
            ViewData["bday"] = System.Web.HttpContext.Current.Session["bday"] as String;
            ViewData["error"] = System.Web.HttpContext.Current.Session["error"] as String;
        }
    }
}

TMDT-Lab06-1212433/TMDT-Lab06-1212433/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <header>
            <div id="logindisplay">
                @if (Request.IsAuthenticated)
                {
                    <text>Welcome <strong>@User.Identity.Name</strong>!
                    [ @Html.ActionLink("Logout", "logout", "auth") ]</text>
                }
                else
                {
                    @:[ @Html.ActionLink("Login", "login", "auth") ]
                }

            </div>
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer></footer>
    </div>
</body>
</html>

TMDT-Lab06-1212433/TMDT-Lab06-1212433/Views/users/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Danh sách nhóm của sinh viên</h2>
@using (Html.BeginForm("SaveSession", "users", FormMethod.Post))
{
    <fieldset>
    <legend>Nhóm 1</legend>
    <table border="1" width="30%">
        <tr style="align-content:center">
            <th>MSSV</th>
            <th>Họ tên</th>
        </tr>
        <tr style="align-content:center">
            <td>1212000</td>
            <td>Nguyễn Văn A</td>
        </tr>
        <tr style="align-content:center">
            <td>1212001</td>
            <td>Nguyễn Thị B</td>
        </tr>
        <tr style="align-content:center">
            <td>1212002</td>
            <td>Lê Văn C</td>
        </tr>
    </table>
</fieldset>
    <fieldset>
        <div>
            Nhập mssv cần xem chi tiết: @Html.TextBox("sessionValue")
        </div>
        <div>
            <input type="submit" id="submitToMethod1" name="submit" value="Chi tiết" />
        </div>
        @ViewData["error"]
        <table border="1" width="30%">
            <tr style="align-content:center">
                <th>MSSV</th>
                <th>Họ tên</th>
                <th>Ngày sinh</th>
            </tr>
            <tr style="align-content:center">
                <td>@ViewData["mssv"]</td>
                <td>@ViewData["name"]</td>
                <td>@ViewData["bday"]</td>
            </tr>
        </table>
    </fieldset>
}